# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TEST_Form_5.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(956, 711)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.listWidget = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 185))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 185))
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(260, 40))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.from_sav_rb = QtGui.QRadioButton(self.frame)
        self.from_sav_rb.setGeometry(QtCore.QRect(10, 20, 691, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_sav_rb.sizePolicy().hasHeightForWidth())
        self.from_sav_rb.setSizePolicy(sizePolicy)
        self.from_sav_rb.setObjectName(_fromUtf8("from_sav_rb"))
        self.from_vxc_rb = QtGui.QRadioButton(self.frame)
        self.from_vxc_rb.setGeometry(QtCore.QRect(10, 0, 681, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_vxc_rb.sizePolicy().hasHeightForWidth())
        self.from_vxc_rb.setSizePolicy(sizePolicy)
        self.from_vxc_rb.setObjectName(_fromUtf8("from_vxc_rb"))
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.qn_file_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qn_file_btn.sizePolicy().hasHeightForWidth())
        self.qn_file_btn.setSizePolicy(sizePolicy)
        self.qn_file_btn.setMinimumSize(QtCore.QSize(160, 25))
        self.qn_file_btn.setMaximumSize(QtCore.QSize(160, 25))
        self.qn_file_btn.setObjectName(_fromUtf8("qn_file_btn"))
        self.horizontalLayout.addWidget(self.qn_file_btn)
        self.qn_file_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qn_file_lbl.sizePolicy().hasHeightForWidth())
        self.qn_file_lbl.setSizePolicy(sizePolicy)
        self.qn_file_lbl.setMinimumSize(QtCore.QSize(300, 25))
        self.qn_file_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.qn_file_lbl.setObjectName(_fromUtf8("qn_file_lbl"))
        self.horizontalLayout.addWidget(self.qn_file_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dt_file_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dt_file_btn.sizePolicy().hasHeightForWidth())
        self.dt_file_btn.setSizePolicy(sizePolicy)
        self.dt_file_btn.setMinimumSize(QtCore.QSize(160, 25))
        self.dt_file_btn.setMaximumSize(QtCore.QSize(160, 25))
        self.dt_file_btn.setObjectName(_fromUtf8("dt_file_btn"))
        self.horizontalLayout_2.addWidget(self.dt_file_btn)
        self.data_file_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_lbl.sizePolicy().hasHeightForWidth())
        self.data_file_lbl.setSizePolicy(sizePolicy)
        self.data_file_lbl.setMinimumSize(QtCore.QSize(300, 25))
        self.data_file_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.data_file_lbl.setObjectName(_fromUtf8("data_file_lbl"))
        self.horizontalLayout_2.addWidget(self.data_file_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prv_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prv_btn.sizePolicy().hasHeightForWidth())
        self.prv_btn.setSizePolicy(sizePolicy)
        self.prv_btn.setMinimumSize(QtCore.QSize(160, 25))
        self.prv_btn.setMaximumSize(QtCore.QSize(160, 25))
        self.prv_btn.setObjectName(_fromUtf8("prv_btn"))
        self.horizontalLayout_3.addWidget(self.prv_btn)
        self.exp_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp_btn.sizePolicy().hasHeightForWidth())
        self.exp_btn.setSizePolicy(sizePolicy)
        self.exp_btn.setMinimumSize(QtCore.QSize(160, 25))
        self.exp_btn.setMaximumSize(QtCore.QSize(160, 25))
        self.exp_btn.setObjectName(_fromUtf8("exp_btn"))
        self.horizontalLayout_3.addWidget(self.exp_btn)
        self.expbn_btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expbn_btn.sizePolicy().hasHeightForWidth())
        self.expbn_btn.setSizePolicy(sizePolicy)
        self.expbn_btn.setMinimumSize(QtCore.QSize(160, 25))
        self.expbn_btn.setMaximumSize(QtCore.QSize(160, 25))
        self.expbn_btn.setObjectName(_fromUtf8("expbn_btn"))
        self.horizontalLayout_3.addWidget(self.expbn_btn)
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 25))
        self.label.setMaximumSize(QtCore.QSize(33, 25))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.fldt = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldt.sizePolicy().hasHeightForWidth())
        self.fldt.setSizePolicy(sizePolicy)
        self.fldt.setMinimumSize(QtCore.QSize(0, 25))
        self.fldt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fldt.setObjectName(_fromUtf8("fldt"))
        self.horizontalLayout_3.addWidget(self.fldt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.outputLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        self.outputLabel.setSizePolicy(sizePolicy)
        self.outputLabel.setMinimumSize(QtCore.QSize(300, 43))
        self.outputLabel.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.outputLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.outputLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.outputLabel.setLineWidth(1)
        self.outputLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.outputLabel.setWordWrap(True)
        self.outputLabel.setIndent(3)
        self.outputLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.verticalLayout.addWidget(self.outputLabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(797, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.webView = QtWebKit.QWebView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Survey Results Previewer", None))
        self.from_sav_rb.setText(_translate("Form", ".csv or .xlsx data file came from a .sav file", None))
        self.from_vxc_rb.setText(_translate("Form", ".csv or .xlsx data file was exported directly from server", None))
        self.qn_file_btn.setText(_translate("Form", "Import Questionnaire File", None))
        self.qn_file_lbl.setText(_translate("Form", "Import Questionnaire File", None))
        self.dt_file_btn.setText(_translate("Form", "Import Data File", None))
        self.data_file_lbl.setText(_translate("Form", "Import Data File", None))
        self.prv_btn.setText(_translate("Form", "Preview Selected", None))
        self.exp_btn.setText(_translate("Form", "Export Current Preview", None))
        self.expbn_btn.setText(_translate("Form", "Export DataBases", None))
        self.label.setText(_translate("Form", "Filters:", None))
        self.outputLabel.setText(_translate("Form", "Output", None))

from PyQt4 import QtWebKit
